load("//shared/bazel/rules/robotpy:build_info_gen.bzl", "generate_robotpy_pybind_build_info")
load("//tunables/src/main/python:robotpy_build_info.bzl", "define_pybind_library", "tunables_extension")

PYBIND_PKGCFG_DEPS = [
    "//tunables:native/tunables/robotpy-native-tunables.pc",
    "//wpiutil:native/wpiutil/robotpy-native-wpiutil.pc",
    "//wpiutil/src/main/python:robotpy-wpiutil.generated_pkgcfg_files",
]

generate_robotpy_pybind_build_info(
    name = "robotpy-tunables-generator",
    additional_srcs = ["//tunables:robotpy-native-tunables.copy_headers"],
    package_root_file = "tunables/__init__.py",
    pkgcfgs = PYBIND_PKGCFG_DEPS,
    yaml_files = glob(["semiwrap/*.yml"]),
)

tunables_extension(
    srcs = glob(["tunables/src/**/*.cpp"]),
    extra_hdrs = glob(["tunables/src/**/*.h"]),
    includes = [
        "tunables",
        "tunables/src",
    ],
)

define_pybind_library(
    name = "robotpy-tunables",
    pkgcfgs = PYBIND_PKGCFG_DEPS,
)
