load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "usbviewer",
    srcs = glob(["*.cpp"]),
    tags = [
        "wpi-example",
    ],
    deps = [
        "//cscore/src/main/native:cscore",
        "//wpigui/src/main/native:wpigui",
        "@bzlmodrio-opencv//libraries/cpp/opencv",
    ],
)
