load("@allwpilib_pip_deps//:requirements.bzl", "requirement")
load("//shared/bazel/rules/robotpy:pytest_util.bzl", "robotpy_py_test")

robotpy_py_test(
    "python_tests",
    srcs = glob(["**/*.py"]),
    deps = [
        "//fields/src/main/python:robotpy-fields",
        requirement("pytest"),
    ],
)
