load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "wpiutil-testlib",
    hdrs = glob(["include/**"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

CATCH2_SRCS = [
    "cpp/TestCatch2.cpp",
    "cpp/catch2main.cpp",
]

cc_test(
    name = "wpiutil-gtest-cpp-test",
    size = "small",
    srcs = glob(
        ["cpp/**"],
        exclude = CATCH2_SRCS,
    ) + ["//wpiutil:generated-test-native-cpp-srcs"],
    linkstatic = True,
    tags = ["no-tsan"],  # TODO(pj.reiniger) Find problem
    deps = [
        ":wpiutil-testlib",
        "//thirdparty/catch2",
        "//thirdparty/googletest",
        "//wpiutil",
        "//wpiutil:nanopb-test-headers",
    ],
)

cc_test(
    name = "wpiutil-catch2-cpp-test",
    size = "small",
    srcs = CATCH2_SRCS,
    linkstatic = True,
    deps = [
        ":wpiutil-testlib",
        "//thirdparty/catch2",
        "//wpiutil",
    ],
)
