load("@allwpilib_pip_deps//:requirements.bzl", "requirement")
load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_java//java:defs.bzl", "java_library")
load("@rules_pkg//:mappings.bzl", "pkg_files")
load("@rules_python//python:defs.bzl", "py_binary")
load("//fields:generate_fields.bzl", "generate_fields")
load("//shared/bazel/rules:cc_rules.bzl", "third_party_cc_lib_helper")
load("//shared/bazel/rules:publishing.bzl", "wpilib_maven_export")

filegroup(
    name = "generated-native-include-files",
    srcs = glob(["src/generated/main/native/include/**/*"]),
    visibility = ["//fields:__subpackages__"],
)

filegroup(
    name = "templates",
    srcs = glob([
        "src/generate/**/*.jinja",
        "src/generate/*.json",
    ]),
)

py_binary(
    name = "generate_fields_script",
    srcs = ["generate_fields.py"],
    data = [
        ":field-jsons",
        ":templates",
    ],
    main = "generate_fields.py",
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [requirement("jinja2")],
)

py_binary(
    name = "convert_apriltag_layouts",
    srcs = ["convert_apriltag_layouts.py"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)

generate_fields(
    name = "generate_fields",
)

write_source_files(
    name = "write_fields",
    diff_args = ["-u"],
    files = {
        "src/generated": ":generate_fields",
    },
    suggested_update_target = "//:write_all",
    tags = ["pregeneration"],
    visibility = ["//visibility:public"],
)

pkg_files(
    name = "field-resource-srcs-pkg",
    srcs = [":generate-resources"],
)

pkg_files(
    name = "field-handwritten-srcs-pkg",
    srcs = [
        "src/main/native/cpp/Field.cpp",
        "src/main/native/cpp/FieldImage.cpp",
        "src/main/native/cpp/FieldTag.cpp",
    ],
)

pkg_files(
    name = "field-image-resource-srcs-pkg",
    srcs = [":generate-image-resources"],
)

third_party_cc_lib_helper(
    name = "generated_cc",
    include_root = "src/generated/main/native/include",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "generated_java",
    srcs = glob(["src/generated/main/java/**/*.java"]),
    visibility = ["//fields:__subpackages__"],
)

java_library(
    name = "field-images-java",
    resource_strip_prefix = "fields/src/main/native/resources",
    resources = FIELD_IMAGES,
    tags = [
        "maven_coordinates=org.wpilib.fields:field-images-java:$(WPILIB_VERSION)",
    ],
    visibility = ["//visibility:public"],
)

wpilib_maven_export(
    name = "field-images-java_publish",
    lib_name = "field-images-java",
    maven_coordinates = "org.wpilib.fields:field-images-java:$(WPILIB_VERSION)",
    visibility = ["//visibility:public"],
)

pkg_files(
    name = "resources",
    srcs = FIELD_JSONS,
    strip_prefix = "src/main/native/resources/",
    visibility = ["//fields:__subpackages__"],
)

filegroup(
    name = "test-resources",
    srcs = glob(["src/test/resources/**"]),
    visibility = ["//fields:__subpackages__"],
)
