load("@allwpilib_pip_deps//:requirements.bzl", "requirement")
load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_python//python:defs.bzl", "py_binary")
load("//fields:generate_fields.bzl", "generate_fields")
load("//shared/bazel/rules:cc_rules.bzl", "third_party_cc_lib_helper")

exports_files([
    "src/generated/main/native/cpp/fields/fields.cpp",
    "src/generated/main/native/cpp/fieldimages/field_images.cpp",
])

filegroup(
    name = "generated-native-include-files",
    srcs = glob(["src/generated/main/native/include/**/*"]),
    visibility = ["//fields:__subpackages__"],
)

filegroup(
    name = "templates",
    srcs = glob([
        "src/generate/**/*.jinja",
        "src/generate/*.json",
    ]),
)

py_binary(
    name = "generate_fields_script",
    srcs = ["generate_fields.py"],
    data = [
        ":templates",
        "//fields/src/main/native:field-jsons",
    ],
    main = "generate_fields.py",
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [requirement("jinja2")],
)

py_binary(
    name = "convert_apriltag_layouts",
    srcs = ["convert_apriltag_layouts.py"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)

generate_fields(
    name = "generate_fields",
)

write_source_files(
    name = "write_fields",
    diff_args = ["-u"],
    files = {
        "src/generated": ":generate_fields",
    },
    suggested_update_target = "//:write_all",
    tags = ["pregeneration"],
    visibility = ["//visibility:public"],
)

third_party_cc_lib_helper(
    name = "generated_cc",
    include_root = "src/generated/main/native/include",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "generated_java",
    srcs = glob(["src/generated/main/java/**/*.java"]),
    visibility = ["//fields:__subpackages__"],
)

filegroup(
    name = "test-resources",
    srcs = glob(["src/test/resources/**"]),
    visibility = ["//fields:__subpackages__"],
)
