load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "test_headers",
    srcs = glob(["include/*.hpp"]),
    includes = ["include"],
    strip_include_prefix = "include",
)

cc_test(
    name = "halsim_ws_server-test",
    size = "small",
    srcs = glob(["cpp/**/*.cpp"]),
    tags = [
        "no-asan",
    ],
    deps = [
        ":test_headers",
        "//simulation/halsim_ws_server/src/main/native:halsim_ws_server",
        "//thirdparty/catch2",
    ],
)
