load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "test-headers",
    testonly = True,
    hdrs = glob(["include/**"]),
    includes = ["include"],
)

cc_test(
    name = "wpilibc-test",
    size = "small",
    srcs = glob([
        "cpp/**",
    ]) + ["//wpilibc:generated-test-native-cpp-srcs"],
    tags = [
        "no-tsan",
        "no-ubsan",
    ],
    deps = [
        ":test-headers",
        "//thirdparty/catch2",
        "//wpilibc",
    ],
)
