# fmt: off
# This file is automatically generated, DO NOT EDIT

from os.path import abspath, join, dirname
_root = abspath(dirname(__file__))

libinit_import = "wpilib._init_wpilib"
depends = ['wpiHal', 'wpiutil', 'ntcore', 'wpimath_cpp', 'wpimath_geometry', 'wpimath_controls', 'wpilibc', 'wpilibc_interfaces', 'wpilibc_event']
pypi_package = 'wpilib'

def get_include_dirs():
    root = "/home/pjreiniger/git/allwpilib/wpilib"
    output = [join(root, "src/main/native/include"), join(root, "src/main/python/generated/rpy-include/wpilib/rpy-include"), join(_root, "src"), join(_root, "..", "wpilibc", "src", "main", "native", "include"), join(_root, "..", "..", "..", "..", "..", "..", "..", "..", "..", "..", "git", "allwpilib", "wpilib", "src", "main", "python", "wpilib", "src")]
    import os
    for d in output:
        if not os.path.exists(d):
            print("----------------------------------------" + d + " does not exist!")
    return output
    # return [join(_root, "include"), join(_root, "rpy-include"), join(_root, "src"), join(_root, "..", "wpilibc", "src", "main", "native", "include"), join(_root, "..", "..", "..", "..", "..", "..", "..", "..", "..", "..", "git", "allwpilib", "wpilib", "src", "main", "python", "wpilib", "src")]

def get_library_dirs():
    return []

def get_library_dirs_rel():
    return []

def get_library_names():
    return []

def get_library_full_names():
    return []