load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_python//python:defs.bzl", "py_binary")
load("//wpiutil:generate.bzl", "generate_wpiutil")

py_binary(
    name = "generate_nanopb",
    srcs = ["generate_nanopb.py"],
    data = [
        "//wpiutil/src/main/native:nanopb_generator",
    ],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//:generation",
    ],
)

filegroup(
    name = "proto_files",
    srcs = glob(["src/test/proto/*.proto"]),
)

generate_wpiutil(
    name = "generate_wpiutil",
    proto_files = ":proto_files",
)

write_source_files(
    name = "write_wpiutil",
    diff_args = ["-u"],
    files = {
        "src/generated/test/native/cpp": ":generate_wpiutil",
    },
    suggested_update_target = "//:write_all",
    tags = ["pregeneration"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "nanopb-test-headers",
    hdrs = glob(["src/generated/test/native/cpp/*.h"]),
    includes = ["src/generated/test/native/cpp"],
    strip_include_prefix = "src/generated/test/native/cpp",
    visibility = ["//wpiutil:__subpackages__"],
)

filegroup(
    name = "generated-test-native-cpp-srcs",
    srcs = glob(["src/generated/test/native/cpp/*"]),
    visibility = ["//wpiutil:__subpackages__"],
)
