load("//shared/bazel/rules/robotpy:build_info_gen.bzl", "generate_robotpy_pybind_build_info")
load("//wpinet/src/main/python:robotpy_pybind_build_info.bzl", "define_pybind_library", "wpinet_extension")

PYBIND_PKGCFG_DEPS = [
    "//wpinet:native/wpinet/robotpy-native-wpinet.pc",
    "//wpiutil:native/wpiutil/robotpy-native-wpiutil.pc",
    "//wpiutil/src/main/python:robotpy-wpiutil.generated_pkgcfg_files",
]

generate_robotpy_pybind_build_info(
    name = "robotpy-wpinet-generator",
    additional_srcs = ["//wpinet:robotpy-native-wpinet.copy_headers"],
    package_root_file = "wpinet/__init__.py",
    pkgcfgs = PYBIND_PKGCFG_DEPS,
    pyproject_toml = "pyproject.toml",
    stripped_include_prefix = "",
    yaml_files = glob(["semiwrap/*.yml"]),
    yml_prefix = "",
)

wpinet_extension(
    srcs = ["wpinet/src/main.cpp"],
    includes = [
        "wpinet/",
    ],
)

define_pybind_library(
    name = "robotpy-wpinet",
    pkgcfgs = PYBIND_PKGCFG_DEPS,
)
