load("@allwpilib_pip_deps//:requirements.bzl", "requirement")
load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_pkg//:mappings.bzl", "pkg_files")
load("@rules_python//python:defs.bzl", "py_binary")
load("//wpimath:generate.bzl", "generate_wpimath")

filegroup(
    name = "generated-native-include-files",
    srcs = glob(["src/generated/main/native/cpp/wpimath/protobuf/*.h"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "generated-native-cpp-srcs",
    srcs = glob(["src/generated/main/native/cpp/**/*.cpp"]),
    visibility = ["//wpimath:__subpackages__"],
)

filegroup(
    name = "proto_java_resources",
    srcs = glob(["src/main/proto/**"]),
    visibility = ["//wpimath:__subpackages__"],
)

filegroup(
    name = "templates",
    srcs = glob(["src/generate/main/java/*.jinja"]),
)

filegroup(
    name = "proto_files",
    srcs = glob(["src/main/proto/**/*.proto"]),
    visibility = ["//wpimath:__subpackages__"],
)

py_binary(
    name = "generate_nanopb",
    srcs = ["generate_nanopb.py"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        requirement("jinja2"),
        "//:generation",
    ],
)

py_binary(
    name = "generate_numbers",
    srcs = ["generate_numbers.py"],
    data = [":templates"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        requirement("jinja2"),
        "//:generation",
    ],
)

py_binary(
    name = "generate_quickbuf",
    srcs = ["generate_quickbuf.py"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//:generation",
    ],
)

py_binary(
    name = "generate_wpimath_py",
    srcs = ["generate_wpimath.py"],
    main = "generate_wpimath.py",
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":generate_nanopb",
        ":generate_numbers",
        ":generate_quickbuf",
    ],
)

generate_wpimath(
    name = "generate_wpimath",
    tags = ["pregeneration"],
)

write_source_files(
    name = "write_wpimath",
    diff_args = ["-u"],
    files = {
        "src/generated": ":generate_wpimath",
    },
    suggested_update_target = "//:write_all",
    tags = ["pregeneration"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "generated_java",
    srcs = glob(["src/generated/main/java/**/*.java"]),
    visibility = ["//wpimath:__subpackages__"],
)

cc_library(
    name = "nanopb-generated-headers",
    hdrs = glob(["src/generated/main/native/cpp/**/*.h"]),
    includes = ["src/generated/main/native/cpp"],
    strip_include_prefix = "src/generated/main/native/cpp",
    visibility = ["//wpimath:__subpackages__"],
)

pkg_files(
    name = "protobuf_hdr_pkg",
    srcs = [":generated-native-include-files"],
    strip_prefix = "src/generated/main/native/cpp/",
    visibility = ["//wpimath:__subpackages__"],
)

py_binary(
    name = "ExponentialProfileModel",
    srcs = ["docs/ExponentialProfile/ExponentialProfileModel.py"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)
