load("@allwpilib_pip_deps//:requirements.bzl", "requirement")
load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_python//python:defs.bzl", "py_binary")
load("//commandsv3:generate.bzl", "generate_commandsv3")

py_binary(
    name = "generate_files",
    srcs = ["generate_files.py"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        requirement("jinja2"),
        "//:generation",
    ],
)

filegroup(
    name = "templates",
    srcs = glob([
        "src/generate/main/**",
        "src/main/proto/**",
    ]) + [
        "//wpilibj:hid_schema",
    ],
)

generate_commandsv3(
    name = "generate_commandsv3",
)

write_source_files(
    name = "write_commandsv3",
    diff_args = ["-u"],
    files = {
        "src/generated": ":generate_commandsv3",
    },
    suggested_update_target = "//:write_all",
    tags = ["pregeneration"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "generated_java",
    srcs = glob(["src/generated/main/java/**/*.java"]),
    visibility = ["//commandsv3:__subpackages__"],
)

filegroup(
    name = "main_proto_srcs",
    srcs = glob(["src/main/proto/**"]),
    visibility = ["//commandsv3:__subpackages__"],
)

filegroup(
    name = "test-resources",
    srcs = glob(["src/test/resources/**"]),
    visibility = ["//commandsv3:__subpackages__"],
)
