load("//shared/bazel/rules:java_rules.bzl", "wpilib_java_junit5_test")

wpilib_java_junit5_test(
    name = "tunables-java-test",
    srcs = glob(["**/*.java"]),
    tags = ["exclusive"],
    deps = [
        "//tunables/src/main/java:tunables-java",
        "//wpiutil/src/main/java:wpiutil-java",
        "@maven//:us_hebi_quickbuf_quickbuf_runtime",
    ],
)
