load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "DevMain-Java",
    srcs = ["org/wpilib/DevMain.java"],
    main_class = "org.wpilib.DevMain",
    deps = [
        "//hal/src/main/java:hal-java",
        "//ntcore/src/main/java:ntcore-java",
        "//telemetry/src/main/java:telemetry-java",
        "//tunables/src/main/java:tunables-java",
        "//wpimath/src/main/java:wpimath-java",
        "//wpiutil/src/main/java:wpiutil-java",
    ],
)
