load("@rules_java//java:defs.bzl", "java_plugin")
load("//shared/bazel/rules:java_rules.bzl", "wpilib_java_library")

wpilib_java_library(
    name = "processor-java",
    srcs = glob(["**/*.java"]),
    extra_source_pkgs = ["//epilogue-processor:resources"],
    maven_artifact_name = "epilogue-processor-java",
    maven_group_id = "org.wpilib.epilogue",
    resource_strip_prefix = "epilogue-processor/src/main/resources/",
    resources = ["//epilogue-processor:resource_files"],
    visibility = ["//visibility:public"],
    runtime_deps = [
        "//commandsv2/src/main/java:commandsv2-java",
    ],
    deps = [
        "//epilogue-runtime/src/main/java:epilogue-java",
        "//telemetry/src/main/java:telemetry-java",
    ],
)

java_plugin(
    name = "plugin",
    processor_class = "org.wpilib.epilogue.processor.AnnotationProcessor",
    visibility = ["//visibility:public"],
    deps = [
        "//epilogue-processor/src/main/java:processor-java",
    ],
)
