load("//shared/bazel/rules:cc_rules.bzl", "wpilib_cc_library", "wpilib_cc_shared_library", "wpilib_cc_static_library")
load("//shared/bazel/rules:packaging.bzl", "package_default_cc_project")
load("//shared/bazel/rules:publishing.bzl", "host_architectures")

wpilib_cc_library(
    name = "halsim_xrp",
    srcs = glob([
        "cpp/*",
        "include/**/*.hpp",
    ]),
    include_license_files = True,
    includes = ["include"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//simulation/halsim_ws_core/src/main/native:halsim_ws_core",
        "//wpinet/src/main/native:wpinet",
    ],
)

wpilib_cc_library(
    name = "halsim_xrp_static",
    srcs = glob([
        "cpp/*",
        "include/**/*.hpp",
    ]),
    copts = [
        "-DHALSIM_InitExtension=HALSIM_InitExtension_XRP",
    ],
    include_license_files = True,
    includes = ["include"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//simulation/halsim_ws_core/src/main/native:halsim_ws_core",
        "//wpinet/src/main/native:wpinet",
    ],
)

wpilib_cc_shared_library(
    name = "shared/halsim_xrp",
    auto_export_windows_symbols = False,
    dynamic_deps = [
        "//wpinet/src/main/native:shared/wpinet",
        "//hal/src/main/native:shared/wpiHal",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":halsim_xrp",
    ],
)

wpilib_cc_static_library(
    name = "static/halsim_xrp",
    static_deps = [
        "//wpinet/src/main/native:static/wpinet",
        "//hal/src/main/native:static/wpiHal",
        "//simulation/halsim_ws_core/src/main/native:static/halsim_ws_core",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":halsim_xrp_static",
    ],
)

package_default_cc_project(
    name = "halsim_xrp",
    architectures = host_architectures,
    maven_artifact_name = "halsim_xrp",
    maven_group_id = "org.wpilib.halsim",
)
