name: 'Setup BuildBuddy acache'
description: 'Sets up the build buddy cache to be readonly / writing based on the presence of environment variables'
runs:
  using: "composite"
  steps:
    - name: Setup without key
      env: 
        API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
      if: ${{ env.API_KEY == '' }}
      run: |
          echo "No API key secret detected, will setup readonly cache"
          echo "build:ci --noremote_upload_local_results" > bazel_auth.rc
          
    - name: Set with key
      env: 
        API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
      if: ${{ env.API_KEY != '' }}
      run: |
          echo "API Key detected!"
          echo "build:build_buddy --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDY_API_KEY }}" > bazel_auth.rc
          echo "build:ci --remote_download_minimal" >> bazel_auth.rc
