load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "DevMain-Java",
    srcs = ["org/wpilib/commands2/DevMain.java"],
    main_class = "org.wpilib.commands2.DevMain",
    deps = [
        "//commandsv2/src/main/java:commandsv2-java",
        "//hal/src/main/java:hal-java",
        "//ntcore/src/main/java:ntcore-java",
        "//wpiannotations/src/main/java:wpiannotations",
        "//wpimath/src/main/java:wpimath-java",
        "//wpiutil/src/main/java:wpiutil-java",
    ],
)
