load("//shared/bazel/rules:java_rules.bzl", "wpilib_java_junit5_test")

wpilib_java_junit5_test(
    name = "wpimath-java-test",
    srcs = glob(["**/*.java"]),
    deps = [
        "//telemetry/src/main/java:telemetry-java",
        "//tunables/src/main/java:tunables-java",
        "//wpimath/src/main/java:wpimath-java",
        "//wpiunits/src/main/java:wpiunits-java",
        "//wpiutil/src/main/java:wpiutil-java",
        "@maven//:io_avaje_avaje_jsonb",
        "@maven//:org_ejml_ejml_java9module",
        "@maven//:us_hebi_quickbuf_quickbuf_runtime",
    ],
)
