# fmt: off
# This file is automatically generated, DO NOT EDIT

from os.path import abspath, join, dirname
_root = abspath(dirname(__file__))

libinit_import = "wpilib.event._init_event"
depends = ['wpilibc', 'wpiHal', 'wpimath_filter', 'wpimath_cpp', 'wpiutil', 'ntcore']
pypi_package = 'wpilib'

def get_include_dirs():
    root = "/home/pjreiniger/git/allwpilib/wpilib"
    output = [join(root, "src/main/native/include"), join(root, "src/main/python/generated/rpy-include/wpilib.event/rpy-include")]
    import os
    for d in output:
        if not os.path.exists(d):
            print("----------------------------------------" + d + " does not exist!")
    return output
    # return [join(_root, "include"), join(_root, "rpy-include")]

def get_library_dirs():
    return []

def get_library_dirs_rel():
    return []

def get_library_names():
    return []

def get_library_full_names():
    return []