# fmt: off
# This file is automatically generated, DO NOT EDIT

from os.path import abspath, join, dirname
_root = abspath(dirname(__file__))

libinit_import = "hal.simulation._init_simulation"
depends = ['wpiutil', 'wpiHal']
pypi_package = 'robotpy-hal'

def get_include_dirs():
    root = "/home/pjreiniger/git/allwpilib/hal"
    output = [join(root, "src/main/native/include"), join(root, "src/main/python/generated/rpy-include/hal.simulation/rpy-include")]
    import os
    for d in output:
        if not os.path.exists(d):
            print("----------------------------------------" + d + " does not exist!")
    return output
    # return [join(_root, "include"), join(_root, "rpy-include")]

def get_library_dirs():
    return []

def get_library_dirs_rel():
    return []

def get_library_names():
    return []

def get_library_full_names():
    return []