load("//apriltag/src/main/python:robotpy_build_info.bzl", "apriltag_extension", "define_pybind_library")
load("//shared/bazel/rules/robotpy:build_info_gen.bzl", "generate_robotpy_pybind_build_info")

PYBIND_PKGCFG_DEPS = [
    "//apriltag/src/main/native:native/apriltag/robotpy-native-apriltag.pc",
    "//telemetry/src/main/native:native/telemetry/robotpy-native-telemetry.pc",
    "//telemetry/src/main/python:robotpy-telemetry.generated_pkgcfg_files",
    "//tunables/src/main/native:native/tunables/robotpy-native-tunables.pc",
    "//tunables/src/main/python:robotpy-tunables.generated_pkgcfg_files",
    "//wpimath/src/main/native:native/wpimath/robotpy-native-wpimath.pc",
    "//wpimath/src/main/python:robotpy-wpimath.generated_pkgcfg_files",
    "//wpiutil/src/main/native:native/wpiutil/robotpy-native-wpiutil.pc",
    "//wpiutil/src/main/python:robotpy-wpiutil.generated_pkgcfg_files",
]

generate_robotpy_pybind_build_info(
    name = "robotpy-apriltag-generator",
    additional_srcs = ["//apriltag/src/main/native:robotpy-native-apriltag.copy_headers"],
    package_root_file = "robotpy_apriltag/__init__.py",
    pkgcfgs = PYBIND_PKGCFG_DEPS,
    yaml_files = glob(["semiwrap/*.yml"]),
)

apriltag_extension(
    srcs = ["robotpy_apriltag/src/main.cpp"],
    includes = [
        "datalog/",
    ],
)

define_pybind_library(
    name = "robotpy-apriltag",
    pkgcfgs = PYBIND_PKGCFG_DEPS,
)
