
load("@rules_python//python:defs.bzl", "py_test", "py_binary")

PROJECTS = [
    "AddressableLED",
    "AprilTagsVision",
    "ArcadeDrive",
    "ArcadeDriveXboxController",
    "ArmBot",
    "ArmBotOffboard",
    "ArmSimulation",
    "CANPDP",
    "DifferentialDriveBot",
    "DigitalCommunication",
    "DriveDistanceOffboard",
    "DutyCycleEncoder",
    "DutyCycleInput",
    "ElevatorProfiledPID",
    "ElevatorSimulation",
    "ElevatorTrapezoidProfile",
    "Encoder",
    "FlywheelBangBangController",
    "FrisbeeBot",
    "GameData",
    "GettingStarted",
    "Gyro",
    "GyroDriveCommands",
    "GyroMecanum",
    "HatchbotInlined",
    "HatchbotTraditional",
    "HidRumble",
    "HttpCamera",
    "I2CCommunication",
    "IntermediateVision",
    "MagicbotSimple",
    "MecanumBot",
    "MecanumDrive",
    "MecanumDriveXbox",
    "Mechanism2d",
    "MotorControl",
    "Physics/src",
    "Physics4Wheel/src",
    "PhysicsMecanum/src",
    "PhysicsSPI/src",
    "PotentiometerPID",
    "QuickVision",
    "RamseteController",
    "Relay",
    "RomiReference",
    "SchedulerEventLogging",
    "SelectCommand",
    "ShuffleBoard",
    "Solenoid",
    "StatefulAutonomous",
    "StateSpaceFlywheel",
    "StateSpaceFlywheelSysId",
    "SwerveBot",
    "SysId",
    "TankDrive",
    "TankDriveXboxController",
    "Timed/src",
    "Ultrasonic",
    "UltrasonicPID",
]


def define_examples():
    for example_folder in PROJECTS:
        py_test(
            name = example_folder + "-test",
            srcs = [":robotpy_entry_point.py",],
            main = "robotpy_entry_point.py",
            args = ["--main", "$(location " + example_folder + "/robot.py)", "test", "--builtin"],
            deps = [":robotpy", ":wrapper"],
            data = [example_folder + "/robot.py"],
        )
        
        py_binary(
            name = example_folder + "-run",
            srcs = [":robotpy_entry_point.py"],
            main = "robotpy_entry_point.py",
            args = ["--main", "$(location " + example_folder + "/robot.py)", "test", "--builtin", "--help"],
            deps = [":robotpy", ":wrapper"],
            data = [example_folder + "/robot.py"],
        )
        
        py_binary(
            name = example_folder + "-som",
            srcs = [":robotpy_entry_point.py"],
            main = "robotpy_entry_point.py",
            args = ["--main", "$(location " + example_folder + "/robot.py)", "sim"],
            deps = [":robotpy", ":wrapper"],
            data = [example_folder + "/robot.py"],
        )
