load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//shared/bazel/rules:packaging.bzl", "package_binary_cc_project")
load("//shared/bazel/rules/gen:gen-resources.bzl", "generate_resources")

generate_resources(
    name = "generate-resources",
    namespace = "dlt",
    prefix = "DLT",
    resource_files = glob(["resources/*"]),
)

cc_binary(
    name = "datalogtool",
    srcs = glob(["cpp/*"]) + [
        ":generate-resources",
        "//tools/datalogtool:generate-version",
    ],
    defines = ["LIBSSH_STATIC"],
    linkopts = select({
        "@platforms//os:osx": [
            "-framework",
            "Kerberos",
        ],
        "@platforms//os:windows": [
            "-DEFAULTLIB:ws2_32.lib",
            "-DEFAULTLIB:advapi32.lib",
            "-DEFAULTLIB:crypt32.lib",
            "-DEFAULTLIB:user32.lib",
            "-SUBSYSTEM:WINDOWS",
        ],
        "@wpilib_toolchains//conditions:linux_x86_64": [],
        "@wpilib_toolchains//constraints/combined:is_cross_compiler": [],
    }),
    tags = [
        "wpi-cpp-gui",
    ],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//datalog/src/main/native:datalog",
        "//glass",
        "//shared/bazel/thirdparty/libssh",
    ],
)

package_binary_cc_project(
    name = "datalogtool",
    maven_artifact_name = "DataLogTool",
    maven_group_id = "org.wpilib.tools",
)
