load("@allwpilib_pip_deps//:requirements.bzl", "requirement")
load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_python//python:defs.bzl", "py_binary")
load("//drivers:generate.bzl", "generate_drivers")
load("//shared/bazel/rules:cc_rules.bzl", "third_party_cc_lib_helper")

filegroup(
    name = "generated-native-include-files",
    srcs = glob(["src/generated/main/native/include/**/*"]),
    visibility = ["//drivers:__subpackages__"],
)

py_binary(
    name = "generate_pwm_motor_controllers",
    srcs = ["generate_pwm_motor_controllers.py"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [requirement("jinja2")],
)

filegroup(
    name = "templates",
    srcs = glob(["src/generate/**"]),
)

generate_drivers(
    name = "generate_drivers",
)

write_source_files(
    name = "write_drivers",
    diff_args = ["-u"],
    files = {
        "src/generated": ":generate_drivers",
    },
    suggested_update_target = "//:write_all",
    tags = ["pregeneration"],
    visibility = ["//visibility:public"],
)

third_party_cc_lib_helper(
    name = "generated_cc",
    include_root = "src/generated/main/native/include",
    src_root = "src/generated/main/native/cpp",
    visibility = ["//drivers:__subpackages__"],
)

filegroup(
    name = "generated_java",
    srcs = glob(["src/generated/main/java/**/*.java"]),
    visibility = ["//drivers:__subpackages__"],
)
