load("//shared/bazel/rules:java_rules.bzl", "wpilib_java_library")

wpilib_java_library(
    name = "tunables-java",
    srcs = glob(["**/*.java"]),
    maven_artifact_name = "tunables-java",
    maven_group_id = "org.wpilib.tunables",
    visibility = ["//visibility:public"],
    deps = [
        "//wpiutil/src/main/java:wpiutil-java",
        "@maven//:io_avaje_avaje_json_core",
        "@maven//:io_avaje_avaje_jsonb",
        "@maven//:us_hebi_quickbuf_quickbuf_runtime",
    ],
)
