# fmt: off
# This file is automatically generated, DO NOT EDIT

from os.path import abspath, join, dirname, realpath
_root = abspath(join(dirname(realpath(__file__)), "..", "..", "..", ".."))

libinit_import = "wpilib.simulation._init_simulation"
depends = ['wpilib_core', 'wpilibc', 'wpiHal', 'wpiutil', 'wpimath_cpp', 'wpimath_controls', 'wpimath_geometry', 'wpimath_kinematics', 'ntcore']
pypi_package = 'wpilib'

def get_include_dirs():
    output = [join(_root, "src/main/native/include"), join(_root, "src/main/python/generated/rpy-include/wpilib.simulation/rpy-include")]
    import os
    for d in output:
        if not os.path.exists(d):
            print("----------------------------------------" + d + " does not exist!")
    return output

def get_library_dirs():
    return []

def get_library_dirs_rel():
    return []

def get_library_names():
    return []

def get_library_full_names():
    return []