
EXAMPLE_FOLDERS = [
    "AddressableLED",
    "ArcadeDrive",
    "ArcadeDriveXboxController",
    "ArmBot",
    "ArmBotOffboard",
    "ArmSimulation",
    "AxisCameraSample",
    "CANPDP",
    "DifferentialDriveBot",
    "DifferentialDrivePoseEstimator",
    "DigitalCommunication",
    "DMA",
    "DriveDistanceOffboard",
    "DutyCycleEncoder",
    "DutyCycleInput",
    "ElevatorProfiledPID",
    "ElevatorSimulation",
    "ElevatorTrapezoidProfile",
    "Encoder",
    "EventLoop",
    "Frisbeebot",
    "GearsBot",
    "GettingStarted",
    "Gyro",
    "GyroDriveCommands",
    "GyroMecanum",
    # "HAL",
    "HatchbotInlined",
    "HatchbotTraditional",
    "HidRumble",
    "I2CCommunication",
    "IntermediateVision",
    "MecanumBot",
    "MecanumControllerCommand",
    "MecanumDrive",
    "MecanumDrivePoseEstimator",
    "Mechanism2d",
    "MotorControl",
    "PotentiometerPID",
    "QuickVision",
    "RamseteCommand",
    "RamseteController",
    "RapidReactCommandBot",
    "Relay",
    "RomiReference",
    # "SchedulerEventLogging",
    "SelectCommand",
    "ShuffleBoard",
    "SimpleDifferentialDriveSimulation",
    "Solenoid",
    "StateSpaceArm",
    "StateSpaceDifferentialDriveSimulation",
    "StateSpaceElevator",
    "StateSpaceFlywheel",
    "StateSpaceFlywheelSysId",
    "SwerveBot",
    "SwerveControllerCommand",
    "SwerveDrivePoseEstimator",
    "TankDrive",
    "TankDriveXboxController",
    "Ultrasonic",
    "UltrasonicPID",
    "UnitTest",
]

COMMANDS_V2_FOLDERS = [
    "command2",
    "emptyclass",
    "instantcommand",
    "parallelcommandgroup",
    "paralleldeadlinegroup",
    "parallelracegroup",
    "pidcommand",
    "pidsubsystem2",
    "profiledpidcommand",
    "profiledpidsubsystem",
    "sequentialcommandgroup",
    "subsystem2",
    "trapezoidprofilecommand",
    "trapezoidprofilesubsystem",
]

TEMPLATES_FOLDERS = [
    "commandbased",
    "commandbasedskeleton",
    "robotbaseskeleton",
    "timed",
    "timedskeleton",
    "timeslice",
    "timesliceskeleton",
]

TESTS_FOLDERS = [
    "AddressableLED",
    "UnitTest",
]