EXAMPLE_FOLDERS = {
    "ArcadeDriveGamepad": ["//commandsv2"],
    "ArmSimulation": ["//commandsv2"],
    "DSGamepadChooser": ["//commandsv2"],
    "DifferentialDriveBot": ["//commandsv2"],
    "DifferentialDrivePoseEstimator": ["//commandsv2"],
    "DriveDistanceOffboard": ["//commandsv2"],
    "DriverStationDisplayAnsi": ["//commandsv2"],
    "DriverStationDisplayLines": ["//commandsv2"],
    "DutyCycleEncoder": ["//commandsv2"],
    "ElevatorExponentialProfile": ["//commandsv2"],
    "ElevatorExponentialSimulation": ["//commandsv2"],
    "ElevatorProfiledPID": ["//commandsv2"],
    "ElevatorSimulation": ["//commandsv2"],
    "ElevatorTrapezoidProfile": ["//commandsv2"],
    "Encoder": ["//commandsv2"],
    "GettingStarted": ["//commandsv2"],
    "Gyro": ["//commandsv2"],
    "HAL": ["//commandsv2"],
    "HatchbotInlined": ["//commandsv2"],
    "HatchbotTraditional": ["//commandsv2"],
    "MecanumBot": ["//commandsv2"],
    "MecanumDrive": ["//commandsv2"],
    "MecanumDrivePoseEstimator": ["//commandsv2"],
    "Mechanism2d": ["//commandsv2"],
    "RapidReactCommandBot": ["//commandsv2"],
    "RomiReference": ["//commandsv2", "//romiVendordep"],
    "SimpleDifferentialDriveSimulation": ["//commandsv2"],
    "StateSpaceArm": ["//commandsv2"],
    "StateSpaceElevator": ["//commandsv2"],
    "StateSpaceFlywheel": ["//commandsv2"],
    "StateSpaceFlywheelSysId": ["//commandsv2"],
    "SwerveBot": ["//commandsv2"],
    "SwerveDrivePoseEstimator": ["//commandsv2"],
    "SysIdRoutine": ["//commandsv2"],
    "TankDriveGamepad": ["//commandsv2"],
    "UnitTest": ["//commandsv2"],
    "XRPReference": ["//commandsv2", "//xrpVendordep"],
    "Xrptimed": ["//commandsv2", "//xrpVendordep"],
}

COMMANDS_V2_FOLDERS = {
    "command2": ["//commandsv2"],
    "emptyclass": [],
    "instantcommand": ["//commandsv2"],
    "parallelcommandgroup": ["//commandsv2"],
    "paralleldeadlinegroup": ["//commandsv2"],
    "parallelracegroup": ["//commandsv2"],
    "sequentialcommandgroup": ["//commandsv2"],
    "subsystem2": ["//commandsv2"],
}

SNIPPET_FOLDERS = {
    "ADXLAccelerometers": [],
    "AccelerometerCollision": [],
    "AccelerometerFilter": [],
    "AddressableLED": [],
    "AnalogAccelerometer": [],
    "AnalogEncoder": [],
    "AnalogInput": [],
    "AnalogPotentiometer": [],
    "AprilTagsVision": ["//cameraserver"],
    "CANPDP": [],
    "DifferentialDrive": [],
    "DigitalCommunication": [],
    "DigitalInput": [],
    "DutyCycleEncoder": [],
    "DutyCycleInput": [],
    "Encoder": [],
    "EncoderDrive": [],
    "EncoderHoming": [],
    "EventLoop": [],
    "FlywheelBangBangController": [],
    "HttpCamera": ["//cameraserver"],
    "I2CCommunication": [],
    "IntermediateVision": ["//cameraserver"],
    "LimitSwitch": [],
    "MecanumDrive": [],
    "MotorControl": [],
    "OnboardIMU": [],
    "ProfiledPIDFeedforward": [],
    "QuickVision": ["//cameraserver"],
    "SelectCommand": ["//commandsv2"],
    "Solenoid": [],
}

TEMPLATE_FOLDERS = {
    "commandv2": ["//commandsv2"],
    "commandv2skeleton": ["//commandsv2"],
    "opmode": ["//commandsv2"],
    "robotbaseskeleton": ["//commandsv2"],
    "timed": ["//commandsv2"],
    "timedskeleton": ["//commandsv2"],
    "timeslice": ["//commandsv2"],
    "timesliceskeleton": ["//commandsv2"],
}

EXAMPLE_TESTS_FOLDERS = {
    "ArmSimulation": [],
    "ElevatorSimulation": [],
    "UnitTest": [],
}

SNIPPET_TESTS_FOLDERS = {
    "DigitalCommunication": [],
    "I2CCommunication": [],
}
