# fmt: off
# This file is automatically generated, DO NOT EDIT

from os.path import abspath, join, dirname, realpath
_root = abspath(join(dirname(realpath(__file__)), "..", "..", "..", ".."))

libinit_import = "robotpy_apriltag._init_apriltag"
depends = ['wpiutil', 'wpimath_cpp']
pypi_package = 'robotpy-apriltag'

def get_include_dirs():
    output = [join(_root, "src/main/native/include"), join(_root, "src/main/python/generated/rpy-include/robotpy_apriltag/rpy-include"), join(_root, "..", "apriltag", "src", "main", "native", "include")]
    import os
    for d in output:
        if not os.path.exists(d):
            print("----------------------------------------" + d + " does not exist!")
    return output

def get_library_dirs():
    return [join(_root, "lib")]

def get_library_dirs_rel():
    return ['lib']

def get_library_names():
    return ['apriltag']

def get_library_full_names():
    return ['libapriltag.so']