# fmt: off
# This file is automatically generated, DO NOT EDIT

from os.path import abspath, join, dirname, realpath
_root = abspath(join(dirname(realpath(__file__)), "..", "..", "..", ".."))

libinit_import = "wpimath_test._init_wpimath_test"
depends = ['wpimath_cpp']
pypi_package = 'wpimath_test'

def get_include_dirs():
    output = [join(_root, "src/main/native/include"), join(_root, "src/main/python/generated/rpy-include/wpimath_test/rpy-include"), join(_root, "..", "..", "..", "..", "..", "..", "..", "..", "..", "..", "git", "allwpilib", "wpimath", "src", "test", "python", "cpp", "wpimath_test", "include")]
    import os
    for d in output:
        if not os.path.exists(d):
            print("----------------------------------------" + d + " does not exist!")
    return output

def get_library_dirs():
    return []

def get_library_dirs_rel():
    return []

def get_library_names():
    return []

def get_library_full_names():
    return []