load("@rules_java//java:java_plugin.bzl", "java_plugin")
load("//shared/bazel/rules:java_rules.bzl", "wpilib_java_library")

filegroup(
    name = "resource_files",
    srcs = glob(["src/main/resources/**"]),
    visibility = ["//javacPlugin:__subpackages__"],
)

wpilib_java_library(
    name = "javacPlugin",
    srcs = glob(["src/main/java/**/*.java"]),
    maven_artifact_name = "javac-plugin-java",
    maven_group_id = "org.wpilib",
    resources = ["//javacPlugin:resource_files"],
    visibility = ["//visibility:public"],
    deps = [
        "//wpiannotations",
    ],
)

java_plugin(
    name = "plugin",
    visibility = ["//visibility:public"],
    deps = [
        ":javacPlugin",
    ],
)
