load("//simulation/halsim_gui/src/main/python:robotpy_build_info.bzl", "define_pybind_library", "halsim_gui_ext_extension")

PKG_CONFIG_DEPS = [
    "//datalog/src/main/native:native/datalog/robotpy-native-datalog.pc",
    "//datalog/src/main/python:robotpy-wpilog.generated_pkgcfg_files",
    "//hal/src/main/native:native/wpihal/robotpy-native-mrclib.pc",
    "//hal/src/main/native:native/wpihal/robotpy-native-wpihal.pc",
    "//hal/src/main/python:robotpy-hal.generated_pkgcfg_files",
    "//ntcore/src/main/native:native/ntcore/robotpy-native-ntcore.pc",
    "//ntcore/src/main/python:pyntcore.generated_pkgcfg_files",
    "//simulation/halsim_gui/src/main/native:native/halsim_gui/robotpy-native-halsim-gui.pc",
    "//wpimath/src/main/native:native/wpimath/robotpy-native-wpimath.pc",
    "//wpimath/src/main/python:robotpy-wpimath.generated_pkgcfg_files",
    "//wpinet/src/main/native:native/wpinet/robotpy-native-wpinet.pc",
    "//wpinet/src/main/python:robotpy-wpinet.generated_pkgcfg_files",
    "//wpiutil/src/main/native:native/wpiutil/robotpy-native-wpiutil.pc",
    "//wpiutil/src/main/python:robotpy-wpiutil.generated_pkgcfg_files",
]

halsim_gui_ext_extension(
    srcs = glob(["halsim_gui/_ext/**/*.cpp"]),
)

define_pybind_library(
    name = "robotpy-halsim-gui",
    pkgcfgs = PKG_CONFIG_DEPS,
)
