load("@allwpilib_pip_deps//:requirements.bzl", "requirement")
load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_python//python:defs.bzl", "py_binary")
load("//ntcore:generate_ntcore.bzl", "generate_ntcore")
load("//shared/bazel/rules:cc_rules.bzl", "third_party_cc_lib_helper")

filegroup(
    name = "generated-native-include-files",
    srcs = glob(["src/generated/main/native/include/**/*"]),
    visibility = ["//ntcore:__subpackages__"],
)

generate_ntcore(
    name = "generate_ntcore",
)

filegroup(
    name = "templates",
    srcs = glob([
        "src/generate/**/*.jinja",
        "src/generate/*.json",
    ]),
)

py_binary(
    name = "generate_topics",
    srcs = ["generate_topics.py"],
    data = [":templates"],
    target_compatible_with = select({
        "@wpilib_toolchains//constraints/is_systemcore:systemcore": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        requirement("jinja2"),
        "//:generation",
    ],
)

write_source_files(
    name = "write_ntcore",
    diff_args = ["-u"],
    files = {
        "src/generated": ":generate_ntcore",
    },
    suggested_update_target = "//:write_all",
    tags = ["pregeneration"],
    visibility = ["//visibility:public"],
)

third_party_cc_lib_helper(
    name = "generated_cc",
    include_root = "src/generated/main/native/include",
    src_excludes = ["src/generated/main/native/cpp/jni/**"],
    src_root = "src/generated/main/native/cpp",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "generated_jni",
    srcs = glob(["src/generated/main/native/cpp/jni/**"]),
    visibility = ["//ntcore:__subpackages__"],
)

filegroup(
    name = "generated_java",
    srcs = glob(["src/generated/main/java/**/*.java"]),
    visibility = ["//ntcore:__subpackages__"],
)

cc_library(
    name = "ntcore_c_headers",
    hdrs = [
        "src/generated/main/native/include/wpi/nt/ntcore_c_types.h",
        "src/main/native/include/wpi/nt/ntcore_c.h",
    ],
    includes = [
        "src/generated/main/native/include",
        "src/main/native/include",
    ],
    visibility = ["//visibility:public"],
)
