load("//shared/bazel/rules:jni_rules.bzl", "wpilib_jni_java_library")

wpilib_jni_java_library(
    name = "wpimath-java",
    srcs = ["//wpimath:generated_java"] + glob(["**/*.java"]),
    exported_plugins = ["//javacPlugin/src/main/java:plugin"],
    generated_java_srcs = ["//wpimath:generated_java"],
    javacopts = [
        "-Xep:UnicodeInCode:OFF",
    ],
    maven_artifact_name = "wpimath-java",
    maven_group_id = "org.wpilib.wpimath",
    native_libs = ["//wpimath:shared/wpimathjni"],
    plugins = [
        "//:avaje_jsonb_generator",
    ],
    proto_srcs = ["//wpimath:proto_files"],
    resource_strip_prefix = "wpimath/src/main/proto",
    resources = ["//wpimath:proto_java_resources"],
    visibility = ["//visibility:public"],
    deps = [
        "//wpiannotations/src/main/java:wpiannotations",
        "//wpiunits/src/main/java:wpiunits-java",
        "//wpiutil/src/main/java:wpiutil-java",
        "@maven//:io_avaje_avaje_json_core",
        "@maven//:io_avaje_avaje_jsonb",
        "@maven//:org_ejml_ejml_java9module",
        "@maven//:us_hebi_quickbuf_quickbuf_runtime",
    ],
)
