load("//shared/bazel/rules:java_rules.bzl", "wpilib_java_library")

wpilib_java_library(
    name = "romiVendordep-java",
    srcs = glob(["**/*.java"]),
    maven_artifact_name = "romiVendordep-java",
    maven_group_id = "org.wpilib.romiVendordep",
    visibility = ["//visibility:public"],
    deps = [
        "//hal/src/main/java:hal-java",
        "//telemetry/src/main/java:telemetry-java",
        "//tunables/src/main/java:tunables-java",
        "//wpilibj/src/main/java:wpilibj-java",
        "//wpiutil/src/main/java:wpiutil-java",
    ],
)
