load("@rules_pkg//:mappings.bzl", "pkg_files")

filegroup(
    name = "resource_files",
    srcs = glob(["src/main/resources/**"]),
    visibility = ["//epilogue-processor:__subpackages__"],
)

pkg_files(
    name = "resources",
    srcs = glob(["src/main/resources/**"]),
    strip_prefix = "src/main/resources/",
    visibility = ["//epilogue-processor:__subpackages__"],
)
