load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "datalog-cpp-test",
    size = "small",
    srcs = glob(["cpp/**/*.cpp"]),
    tags = [
        "exclusive",
        "no-asan",
        "no-tsan",
    ],
    deps = [
        "//datalog/src/main/native:datalog",
        "//thirdparty/catch2",
        "//wpiutil/src/test/native:wpiutil-testlib",
    ],
)
