load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "multiCameraServer-java",
    srcs = ["src/main/java/org/wpilib/Main.java"],
    main_class = "org.wpilib.Main",
    deps = [
        "//cameraserver/src/main/java:cameraserver-java",
        "//cscore/src/main/java:cscore-java",
        "//hal/src/main/java:hal-java",
        "//ntcore/src/main/java:ntcore-java",
        "//wpimath/src/main/java:wpimath-java",
        "//wpiutil/src/main/java:wpiutil-java",
        "@maven//:com_google_code_gson_gson",
    ],
)
