name: Bazel

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Windows Release   (native)", os: windows-2022, action: "test",  opt_type: "-c opt", config: "--config=windows",     }
          # - { name: "Windows Debug     (native)", os: windows-2022, action: "test",  opt_type: "-c dbg", config: "--config=windows",     }
          # - { name: "Windows Fastbuild (native)", os: windows-2022, action: "test",  opt_type: "",       config: "--config=windows",     }
          # - { name: "Windows Release   (arm)",    os: windows-2022, action: "build", opt_type: "-c opt", config: "--config=windows_arm", }
          # - { name: "Windows Debug     (arm)",    os: windows-2022, action: "build", opt_type: "-c dbg", config: "--config=windows_arm", }
          # - { name: "Windows Fastbuild (arm)",    os: windows-2022, action: "build", opt_type: "",       config: "--config=windows_arm", }

    name: "Build ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          architecture: x64

      - id: Setup_build_buddy
        uses: ./.github/actions/setup-build-buddy
        with:
          token: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: bazel ${{ matrix.action }}
        run: bazel --output_user_root=C:\\bazelroot ${{ matrix.action }} -k ... ${{ matrix.opt_type }} --config=ci ${{ matrix.config }} --verbose_failures
        shell: bash

      - name: Publish
        run: bazel --output_user_root=C:\\bazelroot run //:publish ${{ matrix.opt_type }} --config=ci ${{ matrix.config }} --verbose_failures
        shell: bash
  
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: build/bazel_maven

  build-mac:
    name: "Mac"
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "OSX Release (native)",   opt_type: "-c opt",   }
          - { name: "OSX Debug (native)",     opt_type: "-c dbg",   }
          # - { name: "OSX Fastbuild (native)", opt_type: "",         }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - id: Setup_build_buddy
        uses: ./.github/actions/setup-build-buddy
        with:
          token: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: bazel test (release)
        run: bazel test -k ...   --config=ci ${{ matrix.opt_type }} --config=macos --nojava_header_compilation --verbose_failures
        shell: bash

      - name: publish
        run: bazel run //:publish   --config=ci ${{ matrix.opt_type }} --config=macos --nojava_header_compilation --verbose_failures
        shell: bash
  
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: build/bazel_maven

  build-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Linux Release (native)",        os: ubuntu-24.04,   container: "wpilib/ubuntu-base:22.04", action: "test",   opt_type: "-c opt", config: "--config=linux",    }
          - { name: "Linux Debug (native)",          os: ubuntu-24.04,   container: "wpilib/ubuntu-base:22.04", action: "test",   opt_type: "-c dbg", config: "--config=linux",    }
          # - { name: "Linux fastbuild (native)",      os: ubuntu-24.04,   container: "wpilib/ubuntu-base:22.04", action: "test",   opt_type: "",       config: "--config=linux",    }
          
          # - { name: "Linux Release (systemcore)",    os: ubuntu-24.04,   container: "wpilib/ubuntu-base:22.04", action: "build",  opt_type: "-c opt", config: "--config=systemcore",    }
          # - { name: "Linux Debug (systemcore)",      os: ubuntu-24.04,   container: "wpilib/ubuntu-base:22.04", action: "build",  opt_type: "-c dbg", config: "--config=systemcore",    }
          # - { name: "Linux fastbuild (systemcore)",  os: ubuntu-24.04,   container: "wpilib/ubuntu-base:22.04", action: "build",  opt_type: "",       config: "--config=systemcore",    }
          
          - { name: "Linux Release (linuxarm32)",    os: ubuntu-24.04,   container: "wpilib/ubuntu-base:22.04", action: "build",  opt_type: "-c opt", config: "--config=linuxarm32",      }
          - { name: "Linux Debug (linuxarm32)",      os: ubuntu-24.04,   container: "wpilib/ubuntu-base:22.04", action: "build",  opt_type: "-c dbg", config: "--config=linuxarm32",      }

          - { name: "Linux Release (linuxarm64)",    os: ubuntu-24.04,   container: "wpilib/ubuntu-base:22.04", action: "build",  opt_type: "-c opt", config: "--config=linuxarm64",      }
          - { name: "Linux Debug (linuxarm64)",      os: ubuntu-24.04,   container: "wpilib/ubuntu-base:22.04", action: "build",  opt_type: "-c dbg", config: "--config=linuxarm64",      }
    name: "${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: bazelbuild/setup-bazelisk@v3

      - id: Setup_build_buddy
        uses: ./.github/actions/setup-build-buddy
        with:
          token: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: bazel ${{ matrix.action }} (release)
        run: bazel ${{ matrix.action }} ... --config=ci ${{ matrix.opt_type }} ${{ matrix.config }} -k --verbose_failures

      - name: bazel publish (release)
        run: bazel run //:publish --config=ci ${{ matrix.opt_type }} ${{ matrix.config }} -k --verbose_failures

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: build/bazel_maven

  buildifier:
    name: "buildifier"
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.15.x
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: 1.15.x
        id: go

      - name: Install Buildifier
        run: |
          cd $(mktemp -d)
          GO111MODULE=on go get github.com/bazelbuild/buildtools/buildifier@6.0.0

      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Run buildifier
        run: buildifier -warnings all --lint=fix -r .

      - name: Check Output
        run: git --no-pager diff --exit-code HEAD

      - name: Generate diff
        run: git diff HEAD > bazel-lint-fixes.patch
        if: ${{ failure() }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-bazel-lint-fixes
          path: bazel-lint-fixes.patch
        if: ${{ failure() }}

  combine:
    name: Combine
    needs: [build-windows, build-mac, build-linux]
    runs-on: ubuntu-24.04
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false
  
      - uses: actions/checkout@v4
        with:
          repository: wpilibsuite/build-tools

      - run: ls -al
      - uses: actions/download-artifact@v4
        with:
          path: combiner/products/build/allOutputs
      - name: Flatten Artifacts
        run: rsync -a --delete combiner/products/build/allOutputs/*/* combiner/products/build/allOutputs/
        
      - uses: actions/upload-artifact@v4
        with:
          name: Maven
          path: combiner/products/build/allOutputs/edu