name: Bazel

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Windows (native)",             os: windows-2022, action: "test", config: "--config=windows --noenable_bzlmod",      }
          - { name: "Windows (bzlmod)",             os: windows-2022, action: "test", config: "--config=windows --enable_bzlmod",        }

          - {  name: "Windows (arm)",               os: windows-2022, action: "build", config: "--config=windows_arm --noenable_bzlmod", }
          - {  name: "Windows (arm bzlmod)",        os: windows-2022, action: "build", config: "--config=windows_arm --enable_bzlmod",   }

          - {  name: "Windows (roborio)",           os: windows-2022, action: "build", config: "--config=roborio --noenable_bzlmod",      }
          - {  name: "Windows (roborio bzlmod)",    os: windows-2022, action: "build", config: "--config=roborio --enable_bzlmod",     }

          - {  name: "Windows (bullseye32)",        os: windows-2022, action: "build", config: "--config=bullseye32 --noenable_bzlmod",      }
          - {  name: "Windows (bullseye32 bzlmod)", os: windows-2022, action: "build", config: "--config=bullseye32 --enable_bzlmod",  }

          - {  name: "Windows (bullseye64)",        os: windows-2022, action: "build", config: "--config=bullseye64 --noenable_bzlmod",      }
          - {  name: "Windows (bullseye64 bzlmod)", os: windows-2022, action: "build", config: "--config=bullseye64 --enable_bzlmod",  }

          - {  name: "Windows (raspi32)",           os: windows-2022, action: "build", config: "--config=raspi32 --noenable_bzlmod",      }
          - {  name: "Windows (raspi32 bzlmod)",    os: windows-2022, action: "build", config: "--config=raspi32 --enable_bzlmod",     }

    name: "Build ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          architecture: x64

      - name: Build wpimath dependencies
        run: bazel --output_user_root=C:\\bazelroot build wpiutil/... wpimath/src/main/proto/... --config=ci ${{ matrix.config }} --nojava_header_compilation --verbose_failures
        shell: bash

      - name: Build wpimath
        run: bazel --output_user_root=C:\\bazelroot build -k wpimath/... --config=ci ${{ matrix.config }} --local_cpu_resources=1 --nojava_header_compilation --verbose_failures
        shell: bash

      - name: Build allowing failures
        run: bazel --output_user_root=C:\\bazelroot build -k ...   --config=ci ${{ matrix.config }} --nojava_header_compilation --verbose_failures || true
        shell: bash

      - name: Build
        run: bazel --output_user_root=C:\\bazelroot ${{ matrix.action }} -k ...   --config=ci ${{ matrix.config }} --nojava_header_compilation --verbose_failures
        shell: bash
