load("//shared/bazel/rules:cc_rules.bzl", "wpilib_cc_library", "wpilib_cc_shared_library", "wpilib_cc_static_library")
load("//shared/bazel/rules:packaging.bzl", "package_default_cc_project")
load("//shared/bazel/rules/robotpy:build_info_gen.bzl", "generate_robotpy_native_wrapper_build_info")
load("//telemetry/src/main/native:robotpy_build_info.bzl", "define_native_wrapper")

wpilib_cc_library(
    name = "telemetry",
    srcs = glob(["cpp/**"]),
    hdrs = glob(["include/**"]),
    includes = [
        "include",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//wpiutil/src/main/native:wpiutil",
    ],
)

wpilib_cc_shared_library(
    name = "shared/telemetry",
    dynamic_deps = [
        "//wpiutil/src/main/native:shared/wpiutil",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":telemetry",
    ],
)

wpilib_cc_static_library(
    name = "static/telemetry",
    static_deps = [
        "//wpiutil/src/main/native:static/wpiutil",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":telemetry",
    ],
)

package_default_cc_project(
    name = "telemetry",
    maven_artifact_name = "telemetry-cpp",
    maven_group_id = "org.wpilib.telemetry",
)

generate_robotpy_native_wrapper_build_info(
    name = "robotpy-native-telemetry-generator",
    pyproject_toml = "pyproject.toml",
)

define_native_wrapper(
    name = "robotpy-native-telemetry",
    pyproject_toml = "pyproject.toml",
)
